### ISSUE TITLE
进入登录界面死机

### ISSUE THREAD

**Issue by yuzifu** [HeartAndSoul001/ASUS-ROG-STRIX-Z490I-HACKINTOSH#4]
相同主板，用了作者的EFI的配置，移除独显配置，进入登录界面的时候死机，用jettmars/Hackintosh-ROG-STRIX-Z490I的配置也一样。
有些时候是10几秒死机，有些时候是30多秒死机。

**Comment by HeartAndSoul001** [comment]
什么型号独显啊？

**Comment by yuzifu** [comment]
没有独显，使用CPU的核显630

**Comment by HeartAndSoul001** [comment]
@yuzifu 尝试不插网线会不会死机重启

**Comment by yuzifu** [comment]
没有插网线，不知道跟我的SSD硬盘是不是有关系，我的硬盘是三星的850 EVO， 接口是NGFF/M.2

**Comment by HeartAndSoul001** [comment]
@yuzifu 我的EFI不能直接拿来用，需要添加自己的序列号，acpi去掉SSDT-SPPT.aml。如果还有问题就先把intel wifi驱动先禁用再试试

**Comment by HeartAndSoul001** [comment]
> @yuzifu 我的EFI不能直接拿来用，需要添加自己的序列号，acpi去掉SSDT-SPPT.aml。如果还有问题就先把intel wifi驱动先禁用再试试

SSDT-SPPT.aml是关于amd独显的修复，你没有独显，加载这个肯定会有问题的

**Comment by yuzifu** [comment]
独显相关的都去掉了，序列号也都加了，也试过显卡注入12345678

**Comment by HeartAndSoul001** [comment]
Wi-Fi驱动有没有禁用试试

**Comment by yuzifu** [comment]
没禁用 wifi

**Comment by yuzifu** [comment]
使用了其它EFI，不会出现死机了
